# -*- coding: utf-8 -*-
{
    "name":"Delivery Cost",
    "author": "Alejandro Rodriguez, Honduras Open Source",
    "description": "Modulo que calcula el costo de destino para pedidos de ventas, genera una factura al proveedor/transportista",
    "category":"Sale",
    "depends":["base",
           "sale",
            "sale_stock",
            "sale_margin",
            "account",
            "product",
            "purchase"
          ],
    "data": ["views/city_view.xml",
    "views/account_nota_debito.xml",
    "views/reports_view.xml",
    "views/nota_debito_view.xml",
    "views/nota_credito_factura.xml",
    "wizard/import_pricelist_view.xml",
    "views/delivery_view.xml",
    "views/transportista_view.xml",
    "views/sale_fleet_view.xml",
    "views/unidades.xml",
    "views/menu_view.xml",
    "views/account_nota_credito.xml",
    "views/priceslist.xml",
    "views/code_sequence.xml",
    "views/priceslist_data.xml",
    "views/fleet_delivery_view.xml",
    "views/invoice_address.xml",
    "views/update_costprice.xml",
    "views/partner.xml",
    "views/provincia_view.xml",
    #"views/product.xml",
    "reports/recibo_facturas_print.xml",
    "reports/recibo_facturas_print_view.xml",
    #"views/sale_margin_view.xml",
    "wizard/nota_credito_wizard.xml",
    "views/purchase.xml",
    "views/fleet_delivery_liquidacion.xml",
    "reports/sale_api_view.xml",
    "reports/sale_api_print_document.xml",
        ],
    'update_xml' : [
            'security/groups.xml',
            'security/ir.model.access.csv'
    ],
    "auto_install": False,
    "installable": True,
}
